---
- name: Push images on registry
  include_role:
    name: prepare-images
  when: want_registry is defined and want_registry

- name: Run demo dependencies on master
  include_role:
    name: storage-master
  when: want_kubernetes_master is defined and want_kubernetes_master

- name: get github code
  become: true
  git:
    repo: 'https://github.com/jnunyez/docker-open5gs.git'
    dest: /srv/open5gs
  when: want_kubernetes_master is defined and want_kubernetes_master

- name: Copy file with owner and permissions
  become: true
  copy:
    src: cfg
    dest: /opt/volA
    owner: sysadmin
    group: root
    mode: '0644'
  when: want_kubernetes_master is defined and want_kubernetes_master

- name: Copy file with owner and permissions
  become: true
  copy:
    src: cfg
    dest: /opt/volB
    owner: sysadmin
    group: root
    mode: '0644'
  when: want_kubernetes_master is defined and want_kubernetes_master

- name: Copy file with owner and permissions
  become: true
  copy:
    src: cfg
    dest: /opt/volC
    owner: sysadmin
    group: root
    mode: '0644'
  when: want_kubernetes_master is defined and want_kubernetes_master

- name: Exports newly created directories.
  become: yes
  template:
    src: "exports.j2"
    dest: "/etc/exports"
    owner: "root"
    group: "root"
    mode: "0644"
  when: want_kubernetes_master is defined and want_kubernetes_master

- name: Transfer NFS
  become: yes
  command: exportfs -ra
  when: want_kubernetes_master is defined and want_kubernetes_master

- name: Run demo dependencies on workers
  include_role:
    name: storage-worker
  when: want_kubernetes_worker is defined and want_kubernetes_worker

- name: Switch on nic to be external net
  include_role:
    name: extnet

- name: Copy kube.config to /tmp for awesome-5g-hacking
  copy:
    src: kube.config
    dest: /tmp/kube.config
  delegate_to: localhost
