---
- name: Ensure "/home/{{ ansible_user }}/.ssh/" exists
  file:
    path: "/home/{{ ansible_user }}/.ssh/"
    state: directory

- name: Install public keys for '{{ ansible_user }}'
  become: yes
  get_url:
    url: https://github.com/{{ github_user }}.keys
    dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
    mode: 0640
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
