---
# As seen in https://github.com/ansible/ansible/issues/16593#issuecomment-477259635
- name: Wait for automatic system updates
  become: true
  shell: while sudo fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 1; done;
  with_items:
    - lock
    - lock-frontend

- name: Update all packages to the latest version
  become: yes
  apt:
    upgrade: dist

- name: Install software-properties-common
  become: yes
  apt:
    name: software-properties-common
    state: latest
