---
- name: Install dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - curl
    - jq

- name: Ensure ~/.kube/config exists
  file:
    state: directory
    path: ~/.kube/

- name: Upload kube.config
  copy:
    src: kube.config
    dest: ~/.kube/config
    mode: 0644

- name: Clone Voltha repository
  git:
    repo: 'https://github.com/ciena/kind-voltha'
    dest: ~/kind-voltha
    version: master

- name: Include kind-voltha binaries in path
  lineinfile:
    path: ~/.profile
    state: present
    insertafter: EOF
    line: 'PATH=~/kind-voltha/bin:$PATH'

- name: Prepare Voltha deployment script
  copy:
    content: |
             #!/usr/bin/env bash
             source releases/voltha-2.3
             TYPE=minimal DEPLOY_K8S=n WITH_BBSIM=y WITH_RADIUS=y CONFIG_SADIS=y ./voltha up
    dest: ~/kind-voltha/launch-script.sh
    mode: 0755
