---
- name: Install dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - curl
    - jq

- name: Ensure ~/.kube/config exists
  file:
    state: directory
    path: ~/.kube/

- name: Upload kube.config
  copy:
    src: kube.config
    dest: ~/.kube/config
    mode: 0644

- name: Clone Voltha repository
  git:
    repo: 'https://github.com/opencord/kind-voltha.git'
    dest: ~/kind-voltha
    version: master

- name: Include kind-voltha binaries in path
  lineinfile:
    path: ~/.profile
    state: present
    insertafter: EOF
    line: 'PATH=~/kind-voltha/bin:$PATH'

# - name: Modified minimal-env.sh
#   copy:
#     src: minimal-env.sh
#     dest: /home/sysadmin/kind-voltha/minimal-env.sh
#     mode: 0664

# - name: Modified minimal-values.yaml
#   copy:
#     src: minimal-values.yaml
#     dest: /home/sysadmin/kind-voltha/minimal-values.yaml
#     mode: 0664

- name: Modified voltha script
  copy:
    src: onos-service.yaml
    dest: /home/sysadmin/onos-service.yaml
    mode: 0664

- name: Modified voltha script
  copy:
    src: voltha
    dest: /home/sysadmin/kind-voltha/voltha
    mode: 0775


# - name: Prepare Voltha deployment script
#   copy:
#     content: |
#              #!/usr/bin/env bash
#              source releases/voltha-2.3
#              TYPE=minimal DEPLOY_K8S=n WITH_BBSIM=y WITH_RADIUS=y CONFIG_SADIS=y ./voltha up
#     dest: ~/kind-voltha/launch-script.sh
#     mode: 0755

- name: Install snapd
  command: sudo apt install snapd

- name: Install yq
  command: sudo snap install yq

- name: Create a onos-app directory
  file:
    path: /home/sysadmin/kind-voltha/onos-files/onos-apps
    state: directory
    mode: '0755'

- name: Download Autoprovision App
  tags: onos_apps
  include: install-app.yml


- name: Create script to start Voltha & ONOS
  blockinfile:
    path: /home/sysadmin/kind-voltha/start_voltha_onos.sh
    create: yes
    marker: ""
    mode: "1777"
    block: |
      #!/usr/bin/env bash
      cd /home/sysadmin/kind-voltha/
      rm -f started
      export TYPE=full
      export DEPLOY_K8S=no
      export WITH_ONOS=classic
      export INSTALL_ONOS_APPS=yes
      export WITH_BBSIM=no
      export WITH_RADIUS=no
      export CONFIG_SADIS=no
      export NUM_OF_ATOMIX=3
      export NUM_OF_ONOS=2
      source voltha up
      touch started
      echo "STARTED" > started

- name: Up voltha and ONOS
  shell:
    cmd: "/home/sysadmin/kind-voltha/start_voltha_onos.sh"
  args:
    executable: /bin/bash

