---
- name: Install docker.io
  become: yes
  apt:
    update_cache: yes
    autoremove: yes
    state: latest
    name: docker.io

- name: adding existing user '{{ user }}' to group docker
  become: yes
  user:
    name: '{{ user }}'
    groups: docker
    append: yes

- name: setup cgroupdriver as systemd
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: /etc/docker/{{ item }}
    owner: root
    group: root
    mode: 0644
  loop:
    - daemon.json

- name: Ensure docker.service.d directory exists
  become: yes
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory

- name: Enable docker TCP socket
  become: yes
  template:
    src: "override.conf.j2"
    dest: /etc/systemd/system/docker.service.d/override.conf
    owner: root
    group: root
    mode: 0644

- name: enable docker service
  become: yes
  systemd:
    name: docker
    state: started
    enabled: yes
