---
- name: Destroy computer vision yaml
  template:
    src: computer-vision.yaml.j2
    dest: /tmp/computer-vision.yaml

- name: Destroy computer vision
  k8s:
    kubeconfig: /tmp/kube.config
    state: absent
    src: /tmp/computer-vision.yaml
