---
- name: Install nfs kernel
  become: yes
  apt:
    name: nfs-common
    state: latest

- name: make volume
  become: yes
  file:
    path: '/opt/volA'
    state: directory
    recurse: yes
    mode: '1777'

- name: make volume
  become: yes
  file:
    path: '/opt/volB'
    state: directory
    recurse: yes
    mode: '1777'

- name: make volume
  become: yes
  file:
    path: '/opt/volC'
    state: directory
    mode: '1777'

- name: make pv1
  k8s:
    kubeconfig: kube.config
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: pvol-1
      spec:
        capacity:
          storage: 1Gi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      volumeMode: Filesystem
      nfs:
        path: /opt/volA
        server: k8s.local
        readOnly: false
  delegate_to: localhost

- name: make pv
  k8s:
    kubeconfig: kube.config
    state: present
    definition:
      kind: PersistentVolume
      metadata:
        name: pvvol-2
      src: pvol-pgw.yaml
  delegate_to: localhost

- name: make pv
  k8s:
    kubeconfig: kube.config
    state: present
    definition: 
      kind: PersistentVolume
      metadata:
        name: pvvol-3
      src: pvol-pcrf.yaml
  delegate_to: localhost

- name: pv claim
  k8s:
    kubeconfig: kube.config
    state: present
    definition:
      kind: PersistentVolumeClaim
      metadata:
        name: pvvol-1
      src: sgw-claim0-persistentvolumeclaim.yaml
  delegate_to: localhost

- name: pv claim
  k8s:
    kubeconfig: kube.config
    state: present
    definition:
      kind: PersistentVolumeClaim
      metadata:
        name: pvvol-2
      src: pgw-claim0-persistentvolumeclaim.yaml
  delegate_to: localhost

- name: pv claim
  k8s:
    kubeconfig: kube.config
    state: present
    definition:
      kind: PersistentVolumeClaim
      metadata:
        name: pvvol-3
      src: pcrf-claim0-persistentvolumeclaim.yaml
  delegate_to: localhost
