apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvol-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/volA
    server: k8s.local
    readOnly: false
