---
- name: Modify NodePort range
  become: yes
  lineinfile:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
    line: "    - --service-node-port-range={{ apiserver_port_range }}"
    insertafter: '    - --service-cluster-ip-range=10.96.0.0/12'

- name: Wait until apiserver is restarted
  wait_for:
    port: 6443

- name: Create MetalLB namespace
  k8s:
    kubeconfig: kube.config
    state: present
    kind: Namespace
    name: metallb-system
  delegate_to: localhost

- name: Download MetalLB manifest
  get_url:
    url: https://raw.githubusercontent.com/google/metallb/v0.9.3/manifests/metallb.yaml
    dest: /tmp/metallb.yaml
    validate_certs: no
  delegate_to: localhost

- name: Deploy MetalLB
  k8s:
    kubeconfig: kube.config
    state: present
    src: /tmp/metallb.yaml
  delegate_to: localhost

- name: Create secretkey
  shell: openssl rand -base64 128
  register: secretkey
  delegate_to: localhost

- name: Create MetalLB secret
  k8s:
    kubeconfig: kube.config
    state: present
    definition:
      kind: Secret
      metadata:
        namespace: metallb-system
        name: memberlist
      data:
        secretkey: "{{ secretkey.stdout }}"
  delegate_to: localhost

- name: Create MetalLB ConfigMap
  k8s:
    kubeconfig: kube.config
    state: present
    definition:
      kind: ConfigMap
      metadata:
        namespace: metallb-system
        name: config
      data:
        config: |
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - {{ metallb_ip_pool }}
  delegate_to: localhost
