- name: Find external interface
  set_fact:
    external_interface: "{{ ansible_interfaces | difference(['lo',ansible_default_ipv4.alias]) | first }}"

- name: extnet parent ifup
  become: yes
  shell:
    cmd:  |
      ip link set {{ external_interface }} up
      vconfig add {{ external_interface }} 5
      ip link set {{ external_interface }}.5 up
