---
- name: Setup flannel CIDR
  template:
    src: flannel.yaml.j2
    dest: /tmp/flannel.yaml
  delegate_to: localhost

- name: Deploy Flannel SDN
  k8s:
    kubeconfig: kube.config
    state: present
    src: /tmp/flannel.yaml
  delegate_to: localhost
