---
- name: Add WireGuard repository (for Ubuntu < 19.10)
  become: yes
  apt_repository:
    repo: "ppa:wireguard/wireguard"
    state: present
    update_cache: yes

- name: Install wireguard packages (for Ubuntu < 19.10)
  become: yes
  apt:
    name:
      - "wireguard-dkms"
      - "wireguard-tools"
    state: present

- name: Load wireguard packages into kernel
  become: yes
  modprobe:
    name: wireguard
    state: present

- name: Load kernel modules when booting
  become: yes
  template:
    src: wireguard.conf.j2
    dest: /etc/modules-load.d/wireguard.con
    mode: '0644'
