---
- name: Setup calico CIDR
  template:
    src: calico.yaml.j2
    dest: /tmp/calico.yaml
  delegate_to: "{{ deployer }}"

- name: Deploy Calico SDN
  k8s:
    kubeconfig: /tmp/kube.config
    state: present
    src: /tmp/calico.yaml
  delegate_to: "{{ deployer }}"
