---
- name: Define libvirt network
  virt_net:
    name: br-phys
    autostart: yes
    command: create
    xml: '<network><name>5gphysical</name> <forward mode="bridge"/> <bridge name="5gbr0"/></network>'