---
# This task disables swap for Kubernetes node (see https://github.com/kubernetes/kubernetes/pul    l/31996)
# https://github.com/kubernetes/contrib/blob/master/ansible/roles/node/tasks/swapoff.yml
- name: Remove swapfile from /etc/fstab
  become: yes
  mount:
    path: none
    fstype: swap
    state: absent

- name: Disable swap
  become: yes
  command: swapoff -a

- name: Add Google Cloud packages GPG key
  become: yes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
     
- name: Add kubernetes.io apt repository
  become: yes
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install kubeadm
  become: yes
  apt:
    update_cache: yes
    state: latest
    name: kubeadm
