---
- name: Install libvirt and dependencies
  become: yes
  apt:
    state: present
    name:
      - libvirt-daemon
      - libvirt-clients
      - virt-manager
      - bridge-utils
      - netcat
      - qemu
      - qemu-kvm
      - ebtables
      - dmidecode
      - dnsmasq
      - libguestfs-tools

- name: Enable libvirtd and libvirt-guests
  become: yes
  systemd:
    name: "{{ item }}"
    enabled: True
  with_items:
    - libvirtd
    - libvirt-guests

- name: adding existing user '{{ ansible_user }}' to group kvm
  become: yes
  user:
    name: '{{ ansible_user }}'
    groups: kvm
    append: yes

- name: Clone virt-tools
  git:
    repo: 'https://github.com/4km3/vmtools'
    dest: '/tmp/vmtools'
    depth: 1
    force: yes
    accept_hostkey: yes

- name: Install vmtools
  become: yes
  copy:
    remote_src: yes
    src: '/tmp/vmtools/bin/'
    dest: '/usr/local/bin/'
    mode: '0755'

- name: Make vmtools executable
  become: yes
  file:
    path: '/usr/local/bin'
    state: directory
    recurse: yes
    mode: '0755'

- name: vmtools installation cleanup
  become: yes
  file:
    path: '/tmp/vmtools'
    state: absent
