---
- name: Setup multus
  template:
    src: multus.yaml.j2
    dest: /tmp/multus.yaml
  delegate_to: localhost

- name: Deploy Multus
  k8s:
    kubeconfig: kube.config
    state: present
    src: /tmp/multus.yaml
  delegate_to: localhost
