---
dependencies:
    - git
    - vim
    - unzip
    - terraform
    - ansible
    - packer
    - role: vagrant
      when: want_vagrant is defined and want_vagrant
    - role: docker
      when: want_docker is defined and want_docker
    - role: libvirt
      when: want_libvirt is defined and want_libvirt
    - role: avahi
      when: want_avahi is defined and want_avahi
    - role: kubernetes
      when: want_kubernetes is defined and want_kubernetes
