---
- name: Bootstrap cloned image
  tags: bootstap
  hosts: target
  gather_facts: yes
  vars:
    apt_updated: "0"
  roles:
    - sudo
    - user
    - apt
    - role: kvmhost
      when: want_kvmhost is defined and want_kvmhost
